version: "3.3"

services:
    client:
        ports:
            - 3000:3000
        build:
            context: client
            dockerfile: Dockerfile-dev
        image: noirfatale/ugorala-client-dev
        volumes:
            - ./client:/usr/src/app
            - /usr/src/app/node_modules
            - /usr/src/app/.next
        environment: 
            - STRAPI_URL=http://strapi:1337

    strapi:
        image: noirfatale/ugorala-strapi-dev
        env_file: 
            - .env-strapi
        build: 
            context: strapi
            dockerfile: Dockerfile-dev
        volumes:
            - ./strapi:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 1337:1337
    
    admin:
        image: noirfatale/ugorala-admin-dev
        build: 
            context: admin
            dockerfile: Dockerfile-dev
        volumes:
            - ./admin:/usr/src/app
            - /usr/src/app/node_modules
            - /usr/src/app/.next
        ports:
            - 4000:3000
        env_file: 
            - .env-admin