apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: noirfatale/ugorala-admin
          env:
            - name: STRAPI_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: STRAPI_URL
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: SESSION_SECRET
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AWS_SECRET_KEY
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AWS_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AWS_REGION
            - name: BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: BUCKET_NAME
            
---
apiVersion: v1
kind: Service
metadata:
  name: admin-srv
spec:
  type: ClusterIP
  selector:
    app: admin
  ports:
    - name: admin
      protocol: TCP
      port: 4000  # this is the port exposed by the service (admin-srv:4000)
      targetPort: 3000 # this is the port app is running on in the container


